Create ServoTester teleop
nhs-robotics/t-10-code pull request #26
Opened 2024-10-15 23:49 UTC by liambridgers

Allows testing of all CR servos configured on the robot

2024-10-15 23:53 UTC, YoungerMax requested changes
See comments

2024-10-15 23:53 UTC, YoungerMax commented on TeamCode/src/main/java/intothedeep/teleop/ServoTesterRobotConfiguration.java
> +        servos = hardwareMap.getAll(CRServo.class);
This line

2024-10-15 23:53 UTC, YoungerMax commented on TeamCode/src/main/java/intothedeep/teleop/ServoTester.java
> +public class ServoTester extends TeleOpOpMode {
add `TeleOp` to the end of the name

2024-10-15 23:53 UTC, YoungerMax commented on TeamCode/src/main/java/intothedeep/teleop/ServoTesterRobotConfiguration.java
Just for code cleanliness--and this will be quick--move that line into your teleop

2024-10-15 23:58 UTC, liambridgers commented on TeamCode/src/main/java/intothedeep/teleop/ServoTesterRobotConfiguration.java
done

2024-10-15 23:58 UTC, liambridgers commented on TeamCode/src/main/java/intothedeep/teleop/ServoTester.java
> +public class ServoTester extends TeleOpOpMode {
done

2024-10-16 00:00 UTC, YoungerMax approved these changes
awesome!

2024-10-16 00:00 UTC, merged