PositionalMotor Update
nhs-robotics/t-10-code pull request #53
Opened 2024-12-17 23:50 UTC by liambridgers

Rewrite PositionalMotor for readability and integrate PIDController into it

2024-12-17 23:56 UTC, YoungerMax requested changes

2024-12-17 23:56 UTC, YoungerMax commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
>          }
change from "rotation" to "position"

2024-12-17 23:56 UTC, YoungerMax commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
> +        this.pid = new PIDController(0.1, 0, 0);
kP, kI, kD must be set in the constructor because they are never the same for all motors and hardware

2024-12-17 23:56 UTC, YoungerMax commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
> +        currentPositionTicks = motor.getCurrentPosition() + offsetTicks;
this needs to be updated to use PID, for example: `double powerToSetMotorTo = this.pid.calculate(currentPosition, targetPosition)`

2024-12-17 23:56 UTC, YoungerMax commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
> +        currentPositionTicks = motor.getCurrentPosition() + offsetTicks;
**and this is POWER, NOT velocity

2024-12-17 23:56 UTC, YoungerMax commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
use doubles instead of floats please :pray:

2024-12-17 23:56 UTC, YoungerMax commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
I don't believe there is a need for rotation either, just use ticks because they're both arbitrary units. So its just more work and more confusing to use rotation. So just use ticks since everybody knows what ticks are when it comes to encoders

2024-12-18 00:15 UTC, arlanz commented on TeamCode/src/main/java/t10/motion/hardware/PositionalMotor.java
> +    public void setPosition(double rotation) {
Change name to setTarget or setTargetPosition?
Slighltly unclear currently

2024-12-19 20:20 UTC, YoungerMax approved these changes

2024-12-19 20:29 UTC, EJS70 requested changes
rename getPosition to getTargetPosition & getRealPosition to getPositon

2024-12-19 20:32 UTC, EJS70 approved these changes

2024-12-19 20:42 UTC, arlanz approved these changes
With the added comments, looks good.

2024-12-19 20:42 UTC, merged